name: ci
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
      - run: |
          git config --global user.name "ci-bot"
          git config --global user.email "ci-bot@example.com"
          git fetch origin gh-pages
          mike deploy --push -f -u v1.12.x dev -t "v1.12.x (dev)"
          mike list
